version: "3.3"
services:
  chitchat-backend:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    restart: always
    environment:
      DB_URL: "${DB_URL}"
      JWT_SECRET: "${JWT_SECRET}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_ID: "${EMAIL_ID}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      REDIS_HOST: "redis"
      NODE_ENV: "${NODE_ENV}"
    env_file:
      - .env
    working_dir: /app/src
    volumes:
      - .:/app
      - /app/node_modules
  redis:
    image: redis:alpine
    restart: always